### ISSUE TITLE
Can't find any flight yesterday at LFBI

### ISSUE THREAD

**Issue by scls19fr** [ibisek/ognLogbook#1]
Hello,

I'm looking for https://logbook.ibisek.com/reg/LFBI/2020-08-11 but I only see
No records have been found, recorded or we just don't know :P

On an other site I can see
https://ktrax.kisstech.ch/logbook?id=LFBI&tz=2&day=2020-08-11
there was 6 flights.

Any idea what is wrong?

Kind regards

**Comment by scls19fr** [comment]
On http://www.ibisek.com/ Both top right "Feedback" link and bottom left "Tell me here!" link https://contact-forms.appspot.com/showForm/513NR2WG14239 are broken... but definitely nice projects!

**Comment by ibisek** [comment]
Hello there! It is currently in highly experimental state (new bugs introduced every day ;) ) so please be patient. But the trouble with no ladings at all is, however,  remarkable - not encountered such a problem so far. Will change some constants and we'll see if that gets any better. I am preparing a 'deep analysis engine', that shall be more reliable but that is still a bit of work in progress..

**Comment by ibisek** [comment]
Some more beacon processing code was altered not to throw away beacons, such problems will get better now, I hope.
