### ISSUE TITLE
Gliders never land at LFLE

### ISSUE THREAD

**Issue by scls19fr** [ibisek/ognLogbook#2]
Hello,

See for example https://logbook.ibisek.com/loc/LFLE/2020-08-09 (and others days)
there's many departures but no arrivals

Kind regards

**Comment by ibisek** [comment]
just one idea - do you have OGN receiver at the airfield, or .. what is the coverage in your area like? This might be related to out-of coverage issue by sinking under the radar - the aircraft status then gets orphaned and is deleted upon timeout after 8 hours.

**Comment by scls19fr** [comment]
I don't know this airfield but I only found data odd. But it could be a local procedure (switch off FLARM before landing).
According https://www.aerobuzz.fr/aviation-generale/sebastien-chaumontet-lopportunite-de-faire-entrer-les-petits-aeronefs-et-les-drones-dans-le-projet-ogn/ LFLE was airfield where OGN network was first tested.

**Comment by ibisek** [comment]
Some more beacon processing code was altered not to throw away beacons, such problems will get better now, I hope.
